export interface ComponentInfo {
  character: string;
  pinyin: string;
  meaning: string;
}

export const RADICAL_DICTIONARY: Record<string, ComponentInfo> = {
  '木': { character: '木', pinyin: 'mù', meaning: 'tree / wood' },
  '水': { character: '水', pinyin: 'shuǐ', meaning: 'water' },
  '氵': { character: '氵', pinyin: 'shuǐ', meaning: 'water' },
  '火': { character: '火', pinyin: 'huǒ', meaning: 'fire' },
  '灬': { character: '灬', pinyin: 'huǒ', meaning: 'fire' },
  '土': { character: '土', pinyin: 'tǔ', meaning: 'earth / soil' },
  '金': { character: '金', pinyin: 'jīn', meaning: 'gold / metal' },
  '钅': { character: '钅', pinyin: 'jīn', meaning: 'gold / metal' },
  '日': { character: '日', pinyin: 'rì', meaning: 'sun / day' },
  '月': { character: '月', pinyin: 'yuè', meaning: 'moon / month' },
  '人': { character: '人', pinyin: 'rén', meaning: 'person' },
  '亻': { character: '亻', pinyin: 'rén', meaning: 'person' },
  '女': { character: '女', pinyin: 'nǚ', meaning: 'woman / female' },
  '子': { character: '子', pinyin: 'zǐ', meaning: 'child' },
  '口': { character: '口', pinyin: 'kǒu', meaning: 'mouth' },
  '心': { character: '心', pinyin: 'xīn', meaning: 'heart' },
  '忄': { character: '忄', pinyin: 'xīn', meaning: 'heart' },
  '手': { character: '手', pinyin: 'shǒu', meaning: 'hand' },
  '扌': { character: '扌', pinyin: 'shǒu', meaning: 'hand' },
  '目': { character: '目', pinyin: 'mù', meaning: 'eye' },
  '言': { character: '言', pinyin: 'yán', meaning: 'speech' },
  '讠': { character: '讠', pinyin: 'yán', meaning: 'speech' },
  '走': { character: '走', pinyin: 'zǒu', meaning: 'walk' },
  '辶': { character: '辶', pinyin: 'zǒu', meaning: 'walk' },
  '竹': { character: '竹', pinyin: 'zhú', meaning: 'bamboo' },
  '⺮': { character: '⺮', pinyin: 'zhú', meaning: 'bamboo' },
  '艹': { character: '艹', pinyin: 'cǎo', meaning: 'grass / plant' },
  '犭': { character: '犭', pinyin: 'quǎn', meaning: 'dog / animal' },
  '疒': { character: '疒', pinyin: 'nè', meaning: 'sickness' },
  '宀': { character: '宀', pinyin: 'mián', meaning: 'roof' },
  '冖': { character: '冖', pinyin: 'mì', meaning: 'cover' },
  '广': { character: '广', pinyin: 'guǎng', meaning: 'shelter / wide' },
  '厂': { character: '厂', pinyin: 'chǎng', meaning: 'cliff / factory' },
  '弓': { character: '弓', pinyin: 'gōng', meaning: 'bow' },
  '戈': { character: '戈', pinyin: 'gē', meaning: 'spear / weapon' },
  '斤': { character: '斤', pinyin: 'jīn', meaning: 'axe / weight' },
  '方': { character: '方', pinyin: 'fāng', meaning: 'square / direction' },
  '欠': { character: '欠', pinyin: 'qiàn', meaning: 'lack / yawn' },
  '止': { character: '止', pinyin: 'zhǐ', meaning: 'stop' },
  '歹': { character: '歹', pinyin: 'dǎi', meaning: 'bad / death' },
  '殳': { character: '殳', pinyin: 'shū', meaning: 'weapon / hit' },
  '毋': { character: '毋', pinyin: 'wú', meaning: 'do not' },
  '比': { character: '比', pinyin: 'bǐ', meaning: 'compare' },
  '毛': { character: '毛', pinyin: 'máo', meaning: 'hair / fur' },
  '氏': { character: '氏', pinyin: 'shì', meaning: 'clan' },
  '气': { character: '气', pinyin: 'qì', meaning: 'air / gas' },
  '爪': { character: '爪', pinyin: 'zhuǎ', meaning: 'claw' },
  '父': { character: '父', pinyin: 'fù', meaning: 'father' },
  '爻': { character: '爻', pinyin: 'yáo', meaning: 'diagram lines' },
  '爿': { character: '爿', pinyin: 'pán', meaning: 'split wood' },
  '片': { character: '片', pinyin: 'piàn', meaning: 'slice' },
  '牙': { character: '牙', pinyin: 'yá', meaning: 'tooth' },
  '牛': { character: '牛', pinyin: 'niú', meaning: 'cow / ox' },
  '牜': { character: '牜', pinyin: 'niú', meaning: 'cow / ox' },
  '犬': { character: '犬', pinyin: 'quǎn', meaning: 'dog' },
  '玉': { character: '玉', pinyin: 'yù', meaning: 'jade' },
  '王': { character: '王', pinyin: 'wáng', meaning: 'king / jade' },
  '瓜': { character: '瓜', pinyin: 'guā', meaning: 'melon' },
  '瓦': { character: '瓦', pinyin: 'wǎ', meaning: 'tile' },
  '甘': { character: '甘', pinyin: 'gān', meaning: 'sweet' },
  '生': { character: '生', pinyin: 'shēng', meaning: 'life / birth' },
  '用': { character: '用', pinyin: 'yòng', meaning: 'use' },
  '田': { character: '田', pinyin: 'tián', meaning: 'field' },
  '疋': { character: '疋', pinyin: 'pǐ', meaning: 'bolt of cloth' },
  '白': { character: '白', pinyin: 'bái', meaning: 'white' },
  '皮': { character: '皮', pinyin: 'pí', meaning: 'skin' },
  '皿': { character: '皿', pinyin: 'mǐn', meaning: 'dish / vessel' },
  '矛': { character: '矛', pinyin: 'máo', meaning: 'spear' },
  '矢': { character: '矢', pinyin: 'shǐ', meaning: 'arrow' },
  '石': { character: '石', pinyin: 'shí', meaning: 'stone' },
  '示': { character: '示', pinyin: 'shì', meaning: 'spirit / show' },
  '礻': { character: '礻', pinyin: 'shì', meaning: 'spirit / show' },
  '禾': { character: '禾', pinyin: 'hé', meaning: 'grain / crop' },
  '穴': { character: '穴', pinyin: 'xué', meaning: 'cave' },
  '立': { character: '立', pinyin: 'lì', meaning: 'stand' },
  '米': { character: '米', pinyin: 'mǐ', meaning: 'rice' },
  '糸': { character: '糸', pinyin: 'mì', meaning: 'silk / thread' },
  '纟': { character: '纟', pinyin: 'sī', meaning: 'silk / thread' },
  '缶': { character: '缶', pinyin: 'fǒu', meaning: 'jar / pot' },
  '网': { character: '网', pinyin: 'wǎng', meaning: 'net' },
  '罒': { character: '罒', pinyin: 'wǎng', meaning: 'net' },
  '羊': { character: '羊', pinyin: 'yáng', meaning: 'sheep / goat' },
  '羽': { character: '羽', pinyin: 'yǔ', meaning: 'feather / wing' },
  '老': { character: '老', pinyin: 'lǎo', meaning: 'old' },
  '耂': { character: '耂', pinyin: 'lǎo', meaning: 'old' },
  '考': { character: '考', pinyin: 'kǎo', meaning: 'examine' },
  '耳': { character: '耳', pinyin: 'ěr', meaning: 'ear' },
  '聿': { character: '聿', pinyin: 'yù', meaning: 'brush' },
  '肉': { character: '肉', pinyin: 'ròu', meaning: 'meat / flesh' },
  '臣': { character: '臣', pinyin: 'chén', meaning: 'minister' },
  '自': { character: '自', pinyin: 'zì', meaning: 'self' },
  '至': { character: '至', pinyin: 'zhì', meaning: 'arrive' },
  '臼': { character: '臼', pinyin: 'jiù', meaning: 'mortar' },
  '舌': { character: '舌', pinyin: 'shé', meaning: 'tongue' },
  '舛': { character: '舛', pinyin: 'chuǎn', meaning: 'opposite' },
  '舟': { character: '舟', pinyin: 'zhōu', meaning: 'boat / ship' },
  '艮': { character: '艮', pinyin: 'gèn', meaning: 'stopping' },
  '色': { character: '色', pinyin: 'sè', meaning: 'color' },
  '虍': { character: '虍', pinyin: 'hū', meaning: 'tiger' },
  '虫': { character: '虫', pinyin: 'chóng', meaning: 'insect / bug' },
  '血': { character: '血', pinyin: 'xuè', meaning: 'blood' },
  '行': { character: '行', pinyin: 'xíng', meaning: 'walk / go' },
  '衣': { character: '衣', pinyin: 'yī', meaning: 'clothes' },
  '衤': { character: '衤', pinyin: 'yī', meaning: 'clothes' },
  '西': { character: '西', pinyin: 'xī', meaning: 'west' },
  '见': { character: '见', pinyin: 'jiàn', meaning: 'see' },
  '角': { character: '角', pinyin: 'jiǎo', meaning: 'horn / corner' },
  '谷': { character: '谷', pinyin: 'gǔ', meaning: 'valley' },
  '豆': { character: '豆', pinyin: 'dòu', meaning: 'bean' },
  '豕': { character: '豕', pinyin: 'shǐ', meaning: 'pig' },
  '豸': { character: '豸', pinyin: 'zhì', meaning: 'badger / beast' },
  '贝': { character: '贝', pinyin: 'bèi', meaning: 'shell / treasure' },
  '赤': { character: '赤', pinyin: 'chì', meaning: 'red' },
  '足': { character: '足', pinyin: 'zú', meaning: 'foot' },
  '⻀': { character: '⻀', pinyin: 'zú', meaning: 'foot' },
  '身': { character: '身', pinyin: 'shēn', meaning: 'body' },
  '车': { character: '车', pinyin: 'chē', meaning: 'cart / vehicle' },
  '辛': { character: '辛', pinyin: 'xīn', meaning: 'bitter / spicy' },
  '辰': { character: '辰', pinyin: 'chén', meaning: 'dragon / morning' },
  '辵': { character: '辵', pinyin: 'chuò', meaning: 'walk' },
  '邑': { character: '邑', pinyin: 'yì', meaning: 'city' },
  '阝': { character: '阝', pinyin: 'fù / yì', meaning: 'mound / city' },
  '酉': { character: '酉', pinyin: 'yǒu', meaning: 'wine jar' },
  '采': { character: '采', pinyin: 'cǎi', meaning: 'gather' },
  '长': { character: '长', pinyin: 'cháng', meaning: 'long / grow' },
  '门': { character: '门', pinyin: 'mén', meaning: 'door / gate' },
  '隹': { character: '隹', pinyin: 'zhuī', meaning: 'short-tailed bird' },
  '雨': { character: '雨', pinyin: 'yǔ', meaning: 'rain' },
  '青': { character: '青', pinyin: 'qīng', meaning: 'blue / green' },
  '非': { character: '非', pinyin: 'fēi', meaning: 'wrong / non-' },
  '面': { character: '面', pinyin: 'miàn', meaning: 'face' },
  '革': { character: '革', pinyin: 'gé', meaning: 'leather' },
  '韦': { character: '韦', pinyin: 'wéi', meaning: 'tanned leather' },
  '音': { character: '音', pinyin: 'yīn', meaning: 'sound' },
  '页': { character: '页', pinyin: 'yè', meaning: 'page / head' },
  '风': { character: '风', pinyin: 'fēng', meaning: 'wind' },
  '飞': { character: '飞', pinyin: 'fēi', meaning: 'fly' },
  '食': { character: '食', pinyin: 'shí', meaning: 'food / eat' },
  '饣': { character: '饣', pinyin: 'shí', meaning: 'food / eat' },
  '首': { character: '首', pinyin: 'shǒu', meaning: 'head' },
  '香': { character: '香', pinyin: 'xiāng', meaning: 'fragrant' },
  '马': { character: '马', pinyin: 'mǎ', meaning: 'horse' },
  '骨': { character: '骨', pinyin: 'gǔ', meaning: 'bone' },
  '鬼': { character: '鬼', pinyin: 'guǐ', meaning: 'ghost' },
  '鱼': { character: '鱼', pinyin: 'yú', meaning: 'fish' },
  '鸟': { character: '鸟', pinyin: 'niǎo', meaning: 'bird' },
  '鹿': { character: '鹿', pinyin: 'lù', meaning: 'deer' },
  '麦': { character: '麦', pinyin: 'mài', meaning: 'wheat' },
  '麻': { character: '麻', pinyin: 'má', meaning: 'hemp' },
  '黄': { character: '黄', pinyin: 'huáng', meaning: 'yellow' },
  '黍': { character: '黍', pinyin: 'shǔ', meaning: 'millet' },
  '黑': { character: '黑', pinyin: 'hēi', meaning: 'black' },
  '鼎': { character: '鼎', pinyin: 'dǐng', meaning: 'tripod vessel' },
  '鼓': { character: '鼓', pinyin: 'gǔ', meaning: 'drum' },
  '鼠': { character: '鼠', pinyin: 'shǔ', meaning: 'rat / mouse' },
  '鼻': { character: '鼻', pinyin: 'bí', meaning: 'nose' },
  '齿': { character: '齿', pinyin: 'chǐ', meaning: 'tooth' },
  '龙': { character: '龙', pinyin: 'lóng', meaning: 'dragon' },
  '龟': { character: '龟', pinyin: 'guī', meaning: 'turtle' },
  '勺': { character: '勺', pinyin: 'sháo', meaning: 'spoon' },
  '亭': { character: '亭', pinyin: 'tíng', meaning: 'pavilion' },
  '及': { character: '及', pinyin: 'jí', meaning: 'reach / and' },
  '与': { character: '与', pinyin: 'yǔ', meaning: 'and / with' },
  '寸': { character: '寸', pinyin: 'cùn', meaning: 'inch' },
  '工': { character: '工', pinyin: 'gōng', meaning: 'work' },
  '己': { character: '己', pinyin: 'jǐ', meaning: 'self' },
  '巾': { character: '巾', pinyin: 'jīn', meaning: 'towel / scarf' },
  '干': { character: '干', pinyin: 'gān', meaning: 'dry / shield' },
  '幺': { character: '幺', pinyin: 'yāo', meaning: 'tiny / one' },
  '廴': { character: '廴', pinyin: 'yǐn', meaning: 'long stride' },
  '廾': { character: '廾', pinyin: 'gǒng', meaning: 'two hands' },
  '弋': { character: '弋', pinyin: 'yì', meaning: 'shoot' },
  '彡': { character: '彡', pinyin: 'shān', meaning: 'hair / pattern' },
  '彳': { character: '彳', pinyin: 'chì', meaning: 'step' },
};

export function getComponentInfo(char: string): ComponentInfo {
  if (RADICAL_DICTIONARY[char]) {
    return RADICAL_DICTIONARY[char];
  }
  return {
    character: char,
    pinyin: '',
    meaning: ''
  };
}
